# Generated by Django 3.2.9 on 2021-12-29 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill_suppers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitem',
            name='transaction_record',
        ),
        migrations.RemoveField(
            model_name='drillnight',
            name='products',
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='dietary_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='TransactionItem',
        ),
    ]
