# Generated by Django 3.2.9 on 2021-12-30 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drill_suppers', '0002_auto_20211229_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='drill_night',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drill_suppers.drillnight'),
            preserve_default=False,
        ),
    ]
