# Generated by Django 3.2.9 on 2022-01-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill_suppers', '0005_auto_20220101_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecheckoutsession',
            name='checkout_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='status',
            field=models.CharField(choices=[('awaiting_checkout', 'Awaiting Checkout'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='awaiting_checkout', max_length=31),
        ),
    ]
