# Generated by Django 3.2.9 on 2022-01-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill_suppers', '0006_auto_20220101_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillnight',
            name='on_sale',
            field=models.BooleanField(default=True),
        ),
    ]
