# Generated by Django 3.2.9 on 2022-05-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill_suppers', '0007_drillnight_on_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drillnight',
            options={'ordering': ['date_time']},
        ),
        migrations.AddField(
            model_name='drillnight',
            name='annotation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drillnight',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
    ]
